In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [2]:
dataset = pd.read_csv("Training.csv")

print("Dataset Shape:", dataset.shape)

dataset.head()

Dataset Shape: (4920, 133)


,itching,skin_rash,nodal_skin_eruptions,continuous_sneezing,shivering,chills,joint_pain,stomach_pain,acidity,ulcers_on_tongue,...,blackheads,scurring,skin_peeling,silver_like_dusting,small_dents_in_nails,inflammatory_nails,blister,red_sore_around_nose,yellow_crust_ooze,prognosis
0,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
1,0,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
2,1,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
3,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection
4,1,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Fungal infection


In [3]:
X = dataset.drop("prognosis", axis=1)

y = dataset["prognosis"]

print("Features Shape:", X.shape)
print("Target Shape:", y.shape)

Features Shape: (4920, 132)
Target Shape: (4920,)


In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Samples:", len(X_train))
print("Testing Samples:", len(X_test))

Training Samples: 3936
Testing Samples: 984


In [5]:
model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

print("Model Training Completed")

Model Training Completed


In [6]:
y_pred = model.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", round(accuracy * 100, 2), "%")


Accuracy: 100.0 %


In [7]:
print(classification_report(y_test, y_pred))

                                         precision    recall  f1-score   support

(vertigo) Paroymsal  Positional Vertigo       1.00      1.00      1.00        18
                                   AIDS       1.00      1.00      1.00        30
                                   Acne       1.00      1.00      1.00        24
                    Alcoholic hepatitis       1.00      1.00      1.00        25
                                Allergy       1.00      1.00      1.00        24
                              Arthritis       1.00      1.00      1.00        23
                       Bronchial Asthma       1.00      1.00      1.00        33
                   Cervical spondylosis       1.00      1.00      1.00        23
                            Chicken pox       1.00      1.00      1.00        21
                    Chronic cholestasis       1.00      1.00      1.00        15
                            Common Cold       1.00      1.00      1.00        23
                           

In [8]:
print(confusion_matrix(y_test, y_pred))

[[18  0  0 ...  0  0  0]
 [ 0 30  0 ...  0  0  0]
 [ 0  0 24 ...  0  0  0]
 ...
 [ 0  0  0 ... 26  0  0]
 [ 0  0  0 ...  0 22  0]
 [ 0  0  0 ...  0  0 34]]


In [9]:
import pickle

pickle.dump(
    model,
    open("disease_model.pkl", "wb")
)

print("Model Saved Successfully")

Model Saved Successfully


In [10]:
loaded_model = pickle.load(
    open("disease_model.pkl", "rb")
)

print("Model Loaded Successfully")

Model Loaded Successfully


In [11]:
sample = X_test.iloc[[0]]

prediction = loaded_model.predict(sample)

print("Predicted Disease:", prediction[0])

print("Actual Disease:", y_test.iloc[0])

Predicted Disease: Acne
Actual Disease: Acne


In [12]:
sym_des = pd.read_csv("symtoms_df.csv")
precautions = pd.read_csv("precautions_df.csv")
workout = pd.read_csv("workout_df.csv")
description = pd.read_csv("description.csv")
medications = pd.read_csv("medications.csv")
diets = pd.read_csv("diets.csv")

print("All Recommendation Files Loaded")

All Recommendation Files Loaded


In [13]:
print("="*50)
print("DISEASE PREDICTION MODEL")
print("="*50)

print("Algorithm Used : Random Forest")
print("Accuracy       :", round(accuracy*100,2), "%")
print("Dataset Size   :", dataset.shape)

print("="*50)

DISEASE PREDICTION MODEL
Algorithm Used : Random Forest
Accuracy       : 100.0 %
Dataset Size   : (4920, 133)


In [14]:
model = pickle.load(open("disease_model.pkl", "rb"))